export enum UsersActionTypes {
    FOLLOW = "users/FOLLOW",
    UNFOLLOW = "users/UNFOLLOW",
    SET_USERS = "users/SET_USERS",
    SET_CURRENT_PAGE = "users/SET_CURRENT_PAGE",
    SET_TOTAL_USERS_COUNT = "users/SET_TOTAL_USERS_COUNT",
    TOGGLE_IS_FETCHING = "users/TOGGLE_IS_FETCHING",
    TOGGLE_IS_FOLLOWING_IN_PROGRESS = "users/TOGGLE_IS_FOLLOWING_IN_PROGRESS",
}