export enum NavbarActionTypes {
    SET_USER_PHOTO = 'navbar/SET_USER_PHOTO',
    SET_SELECTED_BUTTON_INDEX = 'navbar/SET_SELECTED_BUTTON_INDEX',
    SET_NAVBAR_ITEMS = 'navbar/SET_NAVBAR_ITEMS',
    RESET_NAVBAR_ITEMS = 'navbar/RESET_NAVBAR_ITEMS',
    SET_NEW_MESSAGES_COUNT = 'navbar/SET_NEW_MESSAGES_COUNT'
}
